# Generated by Django 3.2.15 on 2023-01-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('AGE', models.IntegerField()),
                ('GENDER', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], max_length=10)),
                ('PHONE_NUMBER', models.CharField(max_length=10)),
                ('MAIL_ID', models.EmailField(max_length=254)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('Purpose', models.CharField(choices=[('enquiry', 'For Enquiry'), ('place_order', 'Place_Order'), ('return', 'Return'), ('other', 'Other')], max_length=20)),
                ('materials_provide', models.TextField()),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.department'),
        ),
    ]
